// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheMoviePlug.Data;

namespace TheMoviePlug.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210715213251_AlteracaoUtilizadores")]
    partial class AlteracaoUtilizadores
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FilmesUtilizadores", b =>
                {
                    b.Property<int>("ListaFilmesFavId")
                        .HasColumnType("int");

                    b.Property<int>("ListaUtilizadoresFavId")
                        .HasColumnType("int");

                    b.HasKey("ListaFilmesFavId", "ListaUtilizadoresFavId");

                    b.HasIndex("ListaUtilizadoresFavId");

                    b.ToTable("FilmesUtilizadores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TheMoviePlug.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("TheMoviePlug.Models.Filmes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Elenco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Realizador")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visibilidade")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Aventura",
                            Classificacao = "8.6",
                            Elenco = "Harrison Ford, Mark Hamill, Carrie Fisher, Peter Cushing",
                            Imagem = "StarWars_ANewHope.jpg",
                            Lancamento = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "George Lucas",
                            Sinopse = "Luke Skywalker (Mark Hammil) sonha ir para a Academia como seus amigos, mas se vê envolvido em uma guerra intergalática quando seu tio compra dois robôs e com eles encontra uma mensagem da princesa Leia Organa (Carrie Fisher) para o jedi Obi-Wan Kenobi (Alec Guiness) sobre os planos da construção da Estrela da Morte, uma gigantesca estação espacial com capacidade para destruir um planeta.",
                            Titulo = "Star Wars IV - A new hope",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Aventura",
                            Classificacao = "8.7",
                            Elenco = "Harrison Ford, Mark Hamill, Carrie Fisher, Billy Dee Williams",
                            Imagem = "StarWars_TheEmpireStrikesBack.jpg",
                            Lancamento = new DateTime(1980, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Irvin Kershner",
                            Sinopse = "São tempos negros para a Rebelião. Após um devastador ataque à sua base no planeta gelado de Hoth, os Rebeldes separam-se devido às perseguições Imperiais. Luke Skywalker vai em busca do misterioso Mestre Jedi Yoda, nos pântanos de Dagobah, enquanto Han Solo e a Princesa Leia despistam a frota Imperial em direcção à linda Cidade das Nuvens de Bespin. Numa tentativa de converter Luke ao lado negro, o maléfico Darth Vader, atrai o jovem Skywalker para uma armadilha.",
                            Titulo = "Star Wars: Episode V - The Empire Strikes Back",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Aventura",
                            Classificacao = "8.3",
                            Elenco = "Harrison Ford, Mark Hamill, Carrie Fisher, Billy Dee Williams",
                            Imagem = "StarWars_ReturnOfTheJedi.jpg",
                            Lancamento = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Richard Marquand",
                            Sinopse = "No espectacular capítulo final da saga Star Wars, Luke Skywalker e a Princesa Leia têm de ir a Tatooine para libertarem Han Solo, infiltrando-se na fortaleza imunda de Jabba the Hutt, o mais temido vilão da galáxia. Novamente unidos, os Rebeldes juntam forças com as tribos de Ewoks para enfrentarem as forças imperiais na lua floresta de Endor. Entretanto o Imperador e Darth Vader conspiram de forma a trazer Luke para o lado negro, mas o jovem Skywalker está determinado em honrar o espírito Jedi.",
                            Titulo = "Star Wars: Episode VI - Return of the Jedi",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Aventura",
                            Classificacao = "6.5",
                            Elenco = "Ewan McGregor, Liam Neeson, Natalie Portman, Samuel L. Jackson, Jake Lloyd",
                            Imagem = "StarWars_ThePhantomMenace.jpg",
                            Lancamento = new DateTime(1999, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "George Lucas",
                            Sinopse = "A Federação do Comércio, dirigida por Nute Gunray planeia assumir o pacífico mundo de Naboo. O Jedi Qui-Gon Jinn e Obi-Wan Kenobi são enviados para confrontar os líderes. Mas nem tudo corre conforme o plano. Os dois Jedis escapam e, em conjunto com o seu novo amigo Gungan, Jar Jar Binks, avançam para Naboo para advertir a Rainha Amidala, mas droids já começaram a capturar Naboo e a Rainha não está segura aí.",
                            Titulo = "Star Wars: Episode I - The Phantom Menace",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Aventura",
                            Classificacao = "6.5",
                            Elenco = "Ewan McGregor, Natalie Portman, Samuel L. Jackson, Hayden Christensen, Christopher Lee",
                            Imagem = "StarWars_AttackOfTheClones.jpg",
                            Lancamento = new DateTime(2002, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "George Lucas",
                            Sinopse = "Após a tentativa de homicídio da Senadora do planeta Naboo, Padme Amidala, Obi-Wan Kenobi e Anakin Skywalker irão investigar o que sucedeu. No decorrer das investigações, Obi-Wan descobre que há uma ligação entre o atentado e o movimento separatista contra a República, liderado por um ex-jedi. À beira de uma guerra civil, a solução encontrada para a defesa da República Galáctica é a constituição de um exército de clones...",
                            Titulo = "Star Wars: Episode II - Attack of the Clones",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Aventura",
                            Classificacao = "7.5",
                            Elenco = "Ewan McGregor, Natalie Portman, Samuel L. Jackson, Hayden Christensen, Ian McDiarmid",
                            Imagem = "StarWars_RevengeOfTheSith.jpg",
                            Lancamento = new DateTime(2005, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "George Lucas",
                            Sinopse = "No meio da guerra inciada no episódio dois desta saga, Anakin Skywalker perde a fidelidade aos Jedi. Seduzido pelas promessas de poder e tentações do Lado Negro da Força, transforma-se em Darth Vader. Juntos os Lordes Sith organizam um plano de vingança que começa com a exterminação dos Jedi. No confronto com os Sith, Yoda e Obi-Wan, os dois mestres Jedi, darão uma réplica feroz, com os seus sabres de luz. Nesta batalha final, que colocará Anakin contra Obi-Wan, se decidirá o destino da Galáxia.",
                            Titulo = "Star Wars: Episode III - Revenge of the Sith",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "Aventura",
                            Classificacao = "7.9",
                            Elenco = "Adam Driver, Harrison Ford, Sara Maria Forsberg, Mark Hamill, Carrie Fisher",
                            Imagem = "StarWars_TheForceAwakens.jpg",
                            Lancamento = new DateTime(2015, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Jeffrey Jacob Abrams",
                            Sinopse = "Décadas após a queda de Darth Vader e do Império, surge uma nova ameaça: a Primeira Ordem, uma organização sombria que busca minar o poder da República e que tem Kylo Ren (Adam Driver), o General Hux (Domhnall Gleeson) e o Líder Supremo Snoke (Andy Serkis) como principais expoentes. Eles conseguem capturar Poe Dameron (Oscar Isaac), um dos principais pilotos da Resistência, que antes de ser preso envia através do pequeno robô BB-8 o mapa de onde vive o mitológico Luke Skywalker (Mark Hamill).",
                            Titulo = "Star Wars: The Force Awakens",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "Aventura",
                            Classificacao = "7.0",
                            Elenco = "Adam Driver, Mark Hamill, Carrie Fisher",
                            Imagem = "StarWars_TheLastJedi.jpg",
                            Lancamento = new DateTime(2017, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Rian Johnson",
                            Sinopse = "Após encontrar o mítico e recluso Luke Skywalker (Mark Hammil) numa ilha isolada, a jovem Rey (Daisy Ridley) procura entender o balanço da Força a partir dos ensinamentos do mestre jedi. Paralelamente, o Primeiro Império de Kylo Ren (Adam Driver) reorganiza-se para enfrentar a Aliança Rebelde. A saga de Skywalker continua, enquanto os heróis de O Despertar da Força se juntam às lendas galácticas, para uma aventura épica, que desvenda mistérios antigos!",
                            Titulo = "Star Wars: The Last Jedi",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Ação",
                            Classificacao = "6.6",
                            Elenco = "Adam Driver, Carrie Fisher, Mark Hamill",
                            Imagem = "StarWars_TheRiseOfSkywalker.jpg",
                            Lancamento = new DateTime(2019, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Jeffrey Jacob Abrams",
                            Sinopse = "A Lucasfilm e o realizador J.J. Abrams voltam a unir forças para levar os espectadores numa jornada épica para uma galáxia muito, muito distante, com este novo e final capítulo da saga Skywalker, a fascinante conclusão da saga Skywalker, onde vão nascer novas lendas e a batalha final pela liberdade ainda está para chegar.",
                            Titulo = "Star Wars: The Rise of Skywalker",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "Ação",
                            Classificacao = "8.0",
                            Elenco = "Chris Evans, Chris Hemsworth, Robert Downey Jr., Mark Ruffalo",
                            Imagem = "TheAvengers.jpg",
                            Lancamento = new DateTime(2012, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Joss Whedon",
                            Sinopse = "Os mais poderosos heróis da Terra têm de aprender a viver juntos e a lutar como uma equipa, criando os vingadores, impedindo Loki e seu exército alienígena de escravizar a humanidade.",
                            Titulo = "The Avengers",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 11,
                            Categoria = "Aventura",
                            Classificacao = "7.3",
                            Elenco = "Chris Evans, Chris Hemsworth, Robert Downey Jr., Mark Ruffalo",
                            Imagem = "Avengers_AgeOfUltron.jpg",
                            Lancamento = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Joss Whedon",
                            Sinopse = "Quando Tony Stark e Bruce Banner tentam iniciar um programa de manutenção da paz dormente chamado Ultron, as coisas vão terrivelmente erradas, e cabe a heróis mais poderosos da terra parar o vilão Ultron.",
                            Titulo = "Avengers: Age of Ultron",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 12,
                            Categoria = "Ação",
                            Classificacao = "8.4",
                            Elenco = "Chris Hemsworth, Robert Downey Jr., Tom Holland, Mark Ruffalo",
                            Imagem = "Avengers_InfinityWar.jpg",
                            Lancamento = new DateTime(2018, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Anthony Russo, Joe Russo",
                            Sinopse = "Homem de Ferro, Thor, Hulk e os Vingadores se reunem para combater o seu inimigo mais poderoso, o maligno Thanos. Em uma missão para obter todas as seis pedras infinitas, Thanos planeia usá-las para infligir a sua vontade maléfica sobre a realidade.",
                            Titulo = "Avengers: Infinity War",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 13,
                            Categoria = "Aventura",
                            Classificacao = "8.4",
                            Elenco = "Chris Evans, Robert Downey Jr., Tom Holland, Mark Ruffalo",
                            Imagem = "Avengers_Endgame.jpg",
                            Lancamento = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Anthony Russo, Joe Russo",
                            Sinopse = "Após Thanos eliminar metade das criaturas vivas, os Vingadores têm de lidar com a perda de amigos e entes queridos. Com Tony Stark vagando perdido no espaço sem água e comida, Steve Rogers e Natasha Romanov lideram a resistência contra o titã louco.",
                            Titulo = "Avengers: Endgame",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 14,
                            Categoria = "Fantasia",
                            Classificacao = "7.6",
                            Elenco = "Daniel Radcliffe, Rupert Grint, Richard Harris",
                            Imagem = "HarryPotter_AndTheSorcerersStone.jpg",
                            Lancamento = new DateTime(2001, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Chris Columbus",
                            Sinopse = "Harry Potter um órfão que descobre que os seus pais eram feiticeiros e que ele também possui poderes mágicos. Harry Potter passou a maior parte do seu tempo debaixo da escada na casa dos Dursleys, seus tios que não gostam dele. Porém, quando é convidado para estudar na Escola de Feitiços e Magia Hogwart, Harry percebe que existem dois mundos: um é o mundo sem graça dos humanos comuns e o outro é cheio de magia, encanto e fantasia.",
                            Titulo = "Harry Potter and the Sorcerers Stone",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 15,
                            Categoria = "Fantasia",
                            Classificacao = "7.4",
                            Elenco = "Daniel Radcliffe, Emma Watson, Rupert Grint",
                            Imagem = "HarryPotter_AndTheChamberOfSecrets.jpg",
                            Lancamento = new DateTime(2002, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Chris Columbus",
                            Sinopse = "Harry Potter frequenta o segundo ano da «Hogwarts School», uma escola de bruxarias e feitiços. Ele é visitado por um duende doméstico chamado Dobby que o aconselha a não regressar à escola. Harry ignora este aviso e regressa. Ele continua famoso, mas detestado pelos Slytherins, e ainda mais por Snape e Malfoy. De repente, coisas estranhas começam a acontecer: as pessoas começam a ficar petrificadas e ninguém conhece a causa disso. Entretanto Harry continua a ouvir uma voz...",
                            Titulo = "Harry Potter and the Chamber of Secrets",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 16,
                            Categoria = "Fantasia",
                            Classificacao = "7.9",
                            Elenco = "Daniel Radcliffe, Emma Watson, Rupert Grint",
                            Imagem = "HarryPotter_AndThePrisonerOfAzkaban.jpg",
                            Lancamento = new DateTime(2004, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Alfonso Cuarón",
                            Sinopse = "Harry Potter, Ron e Hermione entram na adolescência e voltam à Hogwarts para o terceiro ano lectivo na escola de bruxaria. Em Hogwarts procuram resolver o mistério de um fugitivo, o assassino Sirius Black, que foge da prisão de bruxos de Azkaban e representa uma perigosa ameaça para o jovem bruxo.",
                            Titulo = "Harry Potter and the Prisoner of Azkaban",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 17,
                            Categoria = "Aventura",
                            Classificacao = "7.7",
                            Elenco = "Daniel Radcliffe, Emma Watson, Rupert Grint",
                            Imagem = "HarryPotter_AndTheGobletOfFire.jpg",
                            Lancamento = new DateTime(2005, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "Mike Newell",
                            Sinopse = "O nome de Harry Potter é extraído do Cálice de Fogo, tornando-se assim num dos concorrentes de Hogwarts que irão disputar a glória e o prestígio no Torneio dos Três Feiticeiros realizado entre as três grandes escolas de feiticeiros e onde terá de enfrentar os alunos mais experientes numa série de desafios. Mas quem inscreveu o nome de Harry, visto que não foi ele?",
                            Titulo = "Harry Potter and the Goblet of Fire",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 18,
                            Categoria = "Aventura",
                            Classificacao = "7.5",
                            Elenco = "Daniel Radcliffe, Emma Watson, Rupert Grint",
                            Imagem = "HarryPotter_AndTheOrderOfThePhoenix.jpg",
                            Lancamento = new DateTime(2007, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "David Yates",
                            Sinopse = "Harry regressa para o seu quinto ano de estudos em Hogwarts e descobre que a comunidade de feiticeiros não acredita no seu encontro com Lorde Voldemort. Receando que Albus Dumbledore, o reitor de Hogwarts, esteja a mentir sobre Voldemort de modo a minar o seu poder e usurpar o seu cargo o Ministro da Magia, Cornelius Fudge, nomeia uma nova professora de Defesa contra as Artes Negras, para vigiar Dumbledore e os estudantes de Hogwarts.",
                            Titulo = "Harry Potter and the Order of the Phoenix",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 19,
                            Categoria = "Aventura",
                            Classificacao = "7.6",
                            Elenco = "Daniel Radcliffe, Emma Watson, Rupert Grint",
                            Imagem = "HarryPotter_AndTheHalf-BloodPrince.jpg",
                            Lancamento = new DateTime(2009, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "David Yates",
                            Sinopse = "Voldemort está cada vez mais perigoso, tanto no «Mundo Muggle» quanto no «Mundo Mágico», e Hogwarts deixa de ser um lugar seguro. Harry suspeita de perigos que podem até estar dentro do castelo, mas Dumbledore tem as ideias voltadas para a batalha final, que este sabe que se está a aproximar. Juntos procuram uma forma de acabar com a defesa de Voldemort. Além disso, os estudantes estão sob o ataque de um adversário muito diferente: as hormonas da juventude, que se espalham entre todos.",
                            Titulo = "Harry Potter and the Half-Blood Prince",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 20,
                            Categoria = "Ação",
                            Classificacao = "7.7",
                            Elenco = "Daniel Radcliffe, Emma Watson, Rupert Grint",
                            Imagem = "HarryPotter_AndTheDeathlyHallows_part1.jpg",
                            Lancamento = new DateTime(2010, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "David Yates",
                            Sinopse = "O mundo dos feiticeiros tornou-se um lugar perigoso para todos os que estão contra Voldemort. E os aliados deste continuam a querer o prémio mais desejado: Harry Potter. Este tem de ser entregue a Voldemort... vivo. A única esperança de Potter é encontrar o Horcruxes antes que Voldemort o encontre a ele. Mas enquanto procura por pistas, ele descobre uma lenda muito antiga – a lenda dos Talismãs da Morte. E se esta for verdadeira, pode dar a Voldemort o poder de que ele precisa...",
                            Titulo = "Harry Potter and the Deathly Hallows: Part 1",
                            Visibilidade = true
                        },
                        new
                        {
                            Id = 21,
                            Categoria = "Aventura",
                            Classificacao = "8.1",
                            Elenco = "Daniel Radcliffe, Emma Watson, Rupert Grint",
                            Imagem = "HarryPotter_AndTheDeathlyHallows_part2.jpg",
                            Lancamento = new DateTime(2011, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Realizador = "David Yates",
                            Sinopse = "No épico final, a batalha entre as forças do bem e do mal do mundo dos feiticeiros vai originar uma guerra sem precedentes. Os riscos nunca foram tão elevados e ninguém está seguro. Mas é Harry Potter quem terá de fazer o sacrifício final, pois a luta com Lord Voldemort aproxima-se. Tudo acaba.",
                            Titulo = "Harry Potter and the Deathly Hallows: Part 2",
                            Visibilidade = true
                        });
                });

            modelBuilder.Entity("TheMoviePlug.Models.Links", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilmeFK")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorFK")
                        .HasColumnType("int");

                    b.Property<bool>("Visivel")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FilmeFK");

                    b.HasIndex("UtilizadorFK");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilmeFK = 5,
                            URL = "https://www.example.net/",
                            UtilizadorFK = 13,
                            Visivel = true
                        },
                        new
                        {
                            Id = 2,
                            FilmeFK = 9,
                            URL = "https://www.example.com/breath",
                            UtilizadorFK = 4,
                            Visivel = true
                        },
                        new
                        {
                            Id = 3,
                            FilmeFK = 10,
                            URL = "https://www.example.com/",
                            UtilizadorFK = 10,
                            Visivel = true
                        },
                        new
                        {
                            Id = 4,
                            FilmeFK = 1,
                            URL = "https://www.example.com/bee.php",
                            UtilizadorFK = 31,
                            Visivel = true
                        },
                        new
                        {
                            Id = 5,
                            FilmeFK = 11,
                            URL = "https://example.com/",
                            UtilizadorFK = 22,
                            Visivel = true
                        },
                        new
                        {
                            Id = 6,
                            FilmeFK = 20,
                            URL = "http://www.example.com/addition.html#boundary",
                            UtilizadorFK = 3,
                            Visivel = true
                        },
                        new
                        {
                            Id = 7,
                            FilmeFK = 20,
                            URL = "https://bedroom.example.com/",
                            UtilizadorFK = 27,
                            Visivel = true
                        },
                        new
                        {
                            Id = 8,
                            FilmeFK = 17,
                            URL = "http://www.example.com/argument.php",
                            UtilizadorFK = 10,
                            Visivel = true
                        },
                        new
                        {
                            Id = 9,
                            FilmeFK = 8,
                            URL = "https://example.com/afternoon.aspx",
                            UtilizadorFK = 10,
                            Visivel = true
                        },
                        new
                        {
                            Id = 10,
                            FilmeFK = 3,
                            URL = "http://example.org/actor",
                            UtilizadorFK = 2,
                            Visivel = true
                        },
                        new
                        {
                            Id = 11,
                            FilmeFK = 7,
                            URL = "https://www.example.edu/?arm=action&board=attack",
                            UtilizadorFK = 19,
                            Visivel = true
                        },
                        new
                        {
                            Id = 12,
                            FilmeFK = 21,
                            URL = "https://www.example.org/agreement.php?blow=ball&breath=bat#bottle",
                            UtilizadorFK = 1,
                            Visivel = true
                        },
                        new
                        {
                            Id = 13,
                            FilmeFK = 13,
                            URL = "http://example.com/aftermath.html",
                            UtilizadorFK = 24,
                            Visivel = true
                        },
                        new
                        {
                            Id = 14,
                            FilmeFK = 21,
                            URL = "http://www.example.net/?ball=afterthought",
                            UtilizadorFK = 21,
                            Visivel = true
                        },
                        new
                        {
                            Id = 15,
                            FilmeFK = 16,
                            URL = "http://attraction.example.com/?bed=agreement",
                            UtilizadorFK = 6,
                            Visivel = true
                        },
                        new
                        {
                            Id = 16,
                            FilmeFK = 15,
                            URL = "http://board.example.edu/",
                            UtilizadorFK = 5,
                            Visivel = true
                        },
                        new
                        {
                            Id = 17,
                            FilmeFK = 12,
                            URL = "http://www.example.com/behavior.aspx",
                            UtilizadorFK = 15,
                            Visivel = true
                        },
                        new
                        {
                            Id = 18,
                            FilmeFK = 7,
                            URL = "https://www.example.com/anger.php",
                            UtilizadorFK = 29,
                            Visivel = true
                        },
                        new
                        {
                            Id = 19,
                            FilmeFK = 1,
                            URL = "http://beginner.example.com/bomb",
                            UtilizadorFK = 26,
                            Visivel = true
                        },
                        new
                        {
                            Id = 20,
                            FilmeFK = 2,
                            URL = "http://argument.example.com/",
                            UtilizadorFK = 31,
                            Visivel = true
                        },
                        new
                        {
                            Id = 21,
                            FilmeFK = 4,
                            URL = "https://example.org/",
                            UtilizadorFK = 31,
                            Visivel = true
                        },
                        new
                        {
                            Id = 22,
                            FilmeFK = 6,
                            URL = "https://argument.example.org/aunt/bone.aspx",
                            UtilizadorFK = 31,
                            Visivel = true
                        },
                        new
                        {
                            Id = 23,
                            FilmeFK = 14,
                            URL = "https://www.example.net/airplane.html",
                            UtilizadorFK = 4,
                            Visivel = true
                        },
                        new
                        {
                            Id = 24,
                            FilmeFK = 19,
                            URL = "http://www.example.com/airport.aspx",
                            UtilizadorFK = 20,
                            Visivel = true
                        },
                        new
                        {
                            Id = 25,
                            FilmeFK = 18,
                            URL = "https://example.com/basketball?bat=birthday&acoustics=ants",
                            UtilizadorFK = 28,
                            Visivel = true
                        },
                        new
                        {
                            Id = 26,
                            FilmeFK = 9,
                            URL = "https://example.com/#babies",
                            UtilizadorFK = 1,
                            Visivel = true
                        },
                        new
                        {
                            Id = 27,
                            FilmeFK = 20,
                            URL = "http://books.example.com/angle?bead=argument&birth=belief",
                            UtilizadorFK = 30,
                            Visivel = true
                        },
                        new
                        {
                            Id = 28,
                            FilmeFK = 14,
                            URL = "http://www.example.com/boat/art",
                            UtilizadorFK = 20,
                            Visivel = true
                        },
                        new
                        {
                            Id = 29,
                            FilmeFK = 17,
                            URL = "https://brass.example.com/",
                            UtilizadorFK = 17,
                            Visivel = true
                        },
                        new
                        {
                            Id = 30,
                            FilmeFK = 21,
                            URL = "https://www.example.net/balance/amount",
                            UtilizadorFK = 11,
                            Visivel = true
                        },
                        new
                        {
                            Id = 31,
                            FilmeFK = 3,
                            URL = "http://alarm.example.com/?airport=bath#arithmetic",
                            UtilizadorFK = 23,
                            Visivel = true
                        },
                        new
                        {
                            Id = 32,
                            FilmeFK = 9,
                            URL = "https://www.example.com/anger",
                            UtilizadorFK = 15,
                            Visivel = true
                        },
                        new
                        {
                            Id = 33,
                            FilmeFK = 12,
                            URL = "http://bag.example.com/brake/boat",
                            UtilizadorFK = 7,
                            Visivel = true
                        },
                        new
                        {
                            Id = 34,
                            FilmeFK = 4,
                            URL = "https://baseball.example.org/?believe=balance&account=boat",
                            UtilizadorFK = 12,
                            Visivel = true
                        },
                        new
                        {
                            Id = 35,
                            FilmeFK = 11,
                            URL = "http://example.com/boat/bell#brake",
                            UtilizadorFK = 25,
                            Visivel = true
                        },
                        new
                        {
                            Id = 36,
                            FilmeFK = 12,
                            URL = "http://www.example.com/authority",
                            UtilizadorFK = 12,
                            Visivel = true
                        },
                        new
                        {
                            Id = 37,
                            FilmeFK = 2,
                            URL = "http://www.staggeringbeauty.com/",
                            UtilizadorFK = 13,
                            Visivel = true
                        },
                        new
                        {
                            Id = 38,
                            FilmeFK = 4,
                            URL = "http://www.trypap.com/",
                            UtilizadorFK = 17,
                            Visivel = true
                        },
                        new
                        {
                            Id = 39,
                            FilmeFK = 5,
                            URL = "http://www.heeeeeeeey.com/",
                            UtilizadorFK = 16,
                            Visivel = true
                        },
                        new
                        {
                            Id = 40,
                            FilmeFK = 1,
                            URL = "http://www.cat-bounce.com/",
                            UtilizadorFK = 21,
                            Visivel = true
                        },
                        new
                        {
                            Id = 41,
                            FilmeFK = 18,
                            URL = "https://isitchristmas.com/",
                            UtilizadorFK = 28,
                            Visivel = true
                        },
                        new
                        {
                            Id = 42,
                            FilmeFK = 19,
                            URL = "http://www.randomcolour.com/",
                            UtilizadorFK = 19,
                            Visivel = true
                        },
                        new
                        {
                            Id = 43,
                            FilmeFK = 1,
                            URL = "http://www.hasthelargehadroncolliderdestroyedtheworldyet.com/",
                            UtilizadorFK = 1,
                            Visivel = true
                        },
                        new
                        {
                            Id = 44,
                            FilmeFK = 6,
                            URL = "http://www.koalastothemax.com/",
                            UtilizadorFK = 16,
                            Visivel = true
                        },
                        new
                        {
                            Id = 45,
                            FilmeFK = 8,
                            URL = "http://www.sometimesredsometimesblue.com/",
                            UtilizadorFK = 8,
                            Visivel = true
                        },
                        new
                        {
                            Id = 46,
                            FilmeFK = 11,
                            URL = "http://www.patience-is-a-virtue.org/",
                            UtilizadorFK = 11,
                            Visivel = true
                        },
                        new
                        {
                            Id = 47,
                            FilmeFK = 20,
                            URL = "http://www.rock-paper-scissors-game.com/",
                            UtilizadorFK = 3,
                            Visivel = true
                        });
                });

            modelBuilder.Entity("TheMoviePlug.Models.Utilizadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Email = "jen.alvelos12@fakemail.com",
                            Nome = "Jénifer Lalanda Alvelos Perreira",
                            Telemovel = "916729407"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Email = "banhinhas@fmail.com",
                            Nome = "Ranya Banha ",
                            Telemovel = "934736786"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Email = "dinizrv1@coldmail.com",
                            Nome = "Diniz Ribas Vieira",
                            Telemovel = "913430471"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Email = "lage.benfica1904@fakemail.com",
                            Nome = "Luis Sardo Lage",
                            Telemovel = "919974088"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Email = "melindabb@fakemail.com",
                            Nome = "Melinda Berenguer Barroqueiro",
                            Telemovel = "918860367"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Email = "aleixo.riana@fakemail.com",
                            Nome = "Riana Aleixo",
                            Telemovel = "911933053"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Email = "stelastratiacela@fmail.com",
                            Nome = "Stela Prestes Beiriz Kanté",
                            Telemovel = "961617363"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Email = "selmasesimbra90@fmail.com",
                            Nome = "Selma Bandeira de Sesimbra",
                            Telemovel = "922293804"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Email = "vitalis1904@fakemail.com",
                            Nome = "Kelton Malheiro Vital Junior",
                            Telemovel = "966235761"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Email = "bella.santanaf@fakemail.com",
                            Nome = "Izabella Santana Figueira",
                            Telemovel = "923893150"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Email = "quinzero@fakemail.com",
                            Nome = "Irene Lousã Quinzeiro",
                            Telemovel = "910471369"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Email = "caneirolas@coldmail.com",
                            Nome = "Sandro Roçadas Caneira",
                            Telemovel = "938715651"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            Email = "soniaglx@fakemail.com",
                            Nome = "Sónia Maria Gama de Lisboa",
                            Telemovel = "937926385"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            Email = "naylaaa1992@fmail.com",
                            Nome = "Nayla Brandão de Mota",
                            Telemovel = "967301205"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            Email = "mansinho69@coldmail.com",
                            Nome = "Denzel Manso",
                            Telemovel = "928014257"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            Email = "carolcatela@fakemail.com",
                            Nome = "Carolina Rafaela Lages Catela",
                            Telemovel = "960272329"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            Email = "mariabb1985@fakemail.com",
                            Nome = "Maria Berenguer Barroqueiro",
                            Telemovel = "916387910"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            Email = "pastelbelem@fakemail.com",
                            Nome = "Suzana Lacerda de Belém",
                            Telemovel = "930826337"
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            Email = "pazeamor1@fmail.com",
                            Nome = "Íris Gonçalves Perreira da Paz",
                            Telemovel = "911710703"
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            Email = "robalinho.dario@fmail.com",
                            Nome = "Dario Robalinho",
                            Telemovel = "929859102"
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            Email = "nic1906@fakemail.com",
                            Nome = "Nicolas Caparica Belmiro Antonieta",
                            Telemovel = "924505523"
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            Email = "benfas@fakemail.com",
                            Nome = "Luís Filipe Vieira",
                            Telemovel = "937064844"
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            Email = "varandas.out76@fakemail.com",
                            Nome = "Bruno de Carvalho",
                            Telemovel = "926249717"
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            Email = "bdc.out@coldmail.com",
                            Nome = "Varandas",
                            Telemovel = "929112026"
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            Email = "osdragoes@fakemail.com",
                            Nome = "Jorge Pinto da Costa",
                            Telemovel = "922981151"
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            Email = "tikitaka@fmail.com",
                            Nome = "Pepe Guardiola",
                            Telemovel = "914329411"
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            Email = "manesalahfirmino@fmail.com",
                            Nome = "Kloop",
                            Telemovel = "935392465"
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            Email = "formacao.76@fakemail.com",
                            Nome = "Ruben Amorim",
                            Telemovel = "932380726"
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            Email = "aiphone88@fakemail.com",
                            Nome = "Jorge Jesus",
                            Telemovel = "923840017"
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            Email = "aziado@fakemail.com",
                            Nome = "Sérgio Paulo Marceneiro Conceição",
                            Telemovel = "926249788"
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            Email = "roleta.cabecada@coldmail.com",
                            Nome = "Zinadine Zidane Careca",
                            Telemovel = "921122026"
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            Email = "pino@coldmail.com",
                            Nome = "João Miguel Valente Tavares Oliveira",
                            Telemovel = "927777777"
                        });
                });

            modelBuilder.Entity("FilmesUtilizadores", b =>
                {
                    b.HasOne("TheMoviePlug.Models.Filmes", null)
                        .WithMany()
                        .HasForeignKey("ListaFilmesFavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheMoviePlug.Models.Utilizadores", null)
                        .WithMany()
                        .HasForeignKey("ListaUtilizadoresFavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TheMoviePlug.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TheMoviePlug.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheMoviePlug.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TheMoviePlug.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMoviePlug.Models.Links", b =>
                {
                    b.HasOne("TheMoviePlug.Models.Filmes", "Filme")
                        .WithMany("ListaDeLinks")
                        .HasForeignKey("FilmeFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheMoviePlug.Models.Utilizadores", "Utilizador")
                        .WithMany("ListaLinks")
                        .HasForeignKey("UtilizadorFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("TheMoviePlug.Models.Filmes", b =>
                {
                    b.Navigation("ListaDeLinks");
                });

            modelBuilder.Entity("TheMoviePlug.Models.Utilizadores", b =>
                {
                    b.Navigation("ListaLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
